module.exports = {
    // translate
    CreateInstantInvite: "즉석 초대 생성 권한",
    KickMembers: "멤버 추방 권한",
    BanMembers: "멤버 차단 권한",
    Administrator: "관리자 권한",
    ManageChannels: "채널 관리 권한",
    ManageGuild: "서버 관리 권한",
    AddReactions: "반응 추가 권한",
    ViewAuditLog: "감사 로그 보기 권한",
    PrioritySpeaker: "우선 발언자 권한",
    Stream: "스트림 권한",
    ViewChannel: "채널 보기 권한",
    SendMessages: "메시지 보내기 권한",
    SendTTSMessages: "TTS 메시지 보내기 권한",
    ManageMessages: "메시지 관리 권한",
    EmbedLinks: "링크 첨부 권한",
    AttachFiles: "파일 첨부 권한",
    ReadMessageHistory: "메시지 기록 보기 권한",
    MentionEveryone: "모두 언급 권한",
    UseExternalEmojis: "외부 이모지 사용 권한",
    ViewGuildInsights: "서버 인사이트 보기 권한",
    Connect: "연결 권한",
    Speak: "말하기 권한",
    MuteMembers: "멤버를 음소거 권한",
    DeafenMembers: "멤버를 청각 차단 권한",
    MoveMembers: "멤버 이동 권한",
    UseVAD: "음성 감지 사용 권한",
    ChangeNickname: "별명 변경 권한",
    ManageNicknames: "별명 관리 권한",
    ManageRoles: "역할 관리 권한",
    ManageWebhooks: "웹훅 관리 권한",
    ManageEmojisAndStickers: "이모지 및 스티커 관리 권한",
    ManageGuildExpressions: "서버 표현 관리 권한",
    UseApplicationCommands: "응용 프로그램 명령어 사용 권한",
    RequestToSpeak: "발언 요청 권한",
    ManageEvents: "이벤트 관리 권한",
    ManageThreads: "스레드 관리 권한",
    CreatePublicThreads: "공개 스레드 생성 권한",
    CreatePrivateThreads: "비공개 스레드 생성 권한",
    UseExternalStickers: "외부 스티커 사용 권한",
    SendMessagesInThreads: "스레드에서 메시지 보내기 권한",
    UseEmbeddedActivities: "임베디드 활동 사용 권한",
    ModerateMembers: "멤버 관리 권한",
    ViewCreatorMonetizationAnalytics: "창작자 수익 분석 보기 권한",
    UseSoundboard: "사운드보드 사용 권한",
    UseExternalSounds: "외부 소리 사용 권한",
    SendVoiceMessages: "음성 메시지 보내기 권한"
}